stages:
  - build
  - deploy

build:
  image: node:8
  stage: build
  before_script:
    - npm install
  script:
    - npm run build

deploy:
  image: docker:stable
  variables:
    NANOBOX_USERNAME: davi_carvalho96@hotmail.com
    NANOBOX_PASSWORD: carvalhal96
  stage: deploy
  before_script:
    - apk add --update bash && rm -rf /var/cache/apk/*
    - apk add --update curl && rm -rf /var/cache/apk/*
    - bash -c "$(curl -fsSL https://s3.amazonaws.com/tools.nanobox.io/bootstrap/ci.sh)"
  script:
    - nanobox remote add tearful-town
    - nanobox deploy
  only:
    - master
